export const mdList = [
  {
    img: 'baseballUniform',
    name: '야구 유니폼',
    price: 38000,
    width: '26.7rem',
    height: '26.7rem',
  },
  {
    img: 'rugbyUniform',
    name: '럭비 유니폼',
    price: 39000,
    width: '26.7rem',
    height: '26.7rem',
  },
  {
    img: 'wowBadge',
    name: '와우 금속 뱃지',
    price: 6000,
    width: '22.9rem',
    height: '22.9rem',
  },
  {
    img: 'bandana',
    name: '반다나',
    price: 5000,
    width: '27.5rem',
    height: '27.5rem',
  },
  {
    img: 'wowTatto',
    name: '와우 타투 스티커',
    price: 1500,
    width: '13.7rem',
    height: '19.7rem',
  },
  {
    img: 'wowWdfSeal',
    name: 'WOW DJ FESTIVAL 띠부씰 2EA (랜덤)',
    price: 1000,
    width: '28.1rem',
    height: '28.1rem',
  },
  {
    img: 'wowWdfStickerPack',
    name: 'WOW DJ FESTIVAL 스티커 패키지',
    price: 4000,
    width: '26.2rem',
    height: '26.2rem',
  },
  {
    img: 'wdfSlogan',
    name: 'WOW DJ FESTIVAL 슬로건 타올',
    price: 6000,
    width: '33.5rem',
    height: '33.9rem',
  },
  {
    img: 'wowWdfTshirt',
    name: 'WOW DJ FESTIVAL 티셔츠',
    price: 9000,
    width: '28.6rem',
    height: '26.6rem',
  },
  {
    img: 'stringBag',
    name: 'WOW DJ FESTIVAL 스트링백',
    price: 9000,
    width: '26.3rem',
    height: '26.3rem',
  },
];
