export const mdList = [
  {
    img: 'baseballUniform',
    name: 'baseballUniform',
    price: 38000,
    width: '26.7rem',
    height: '26.7rem',
  },
  {
    img: 'rugbyUniform',
    name: 'rugbyUniform',
    price: 39000,
    width: '26.7rem',
    height: '26.7rem',
  },
  {
    img: 'wowBadge',
    name: 'wowBadge',
    price: 6000,
    width: '22.9rem',
    height: '22.9rem',
  },
  {
    img: 'bandana',
    name: 'bandana',
    price: 5000,
    width: '27.5rem',
    height: '27.5rem',
  },
  {
    img: 'wowTatto',
    name: 'wowTatto',
    price: 1500,
    width: '13.7rem',
    height: '19.7rem',
  },
  {
    img: 'wowWdfSeal',
    name: 'wowWdfSeal',
    price: 1000,
    width: '28.1rem',
    height: '28.1rem',
  },
  {
    img: 'wowWdfStickerPack',
    name: 'wowWdfStickerPack',
    price: 4000,
    width: '26.2rem',
    height: '26.2rem',
  },
  {
    img: 'wdfSlogan',
    name: 'wdfSlogan',
    price: 6000,
    width: '33.5rem',
    height: '33.9rem',
  },
  {
    img: 'wowWdfTshirt',
    name: 'wowWdfTshirt',
    price: 9000,
    width: '28.6rem',
    height: '26.6rem',
  },
  {
    img: 'stringBag',
    name: 'stringBag',
    price: 8000,
    width: '26.3rem',
    height: '26.3rem',
  },
];
