export const PubList = (t) => {
  return {
    1: [
      {
        department: t('booth.pub.card.1.0.department'),
        intro: t('booth.pub.card.1.0.intro'),
        event: t('booth.pub.card.1.0.event'),
        food: t('booth.pub.card.1.0.food'),
        wow: () => import('@/assets/webps/booth/wow/37.webp'),
        time: 'all',
      },
    ],
    2: [
      {
        department: t('booth.pub.card.2.0.department'),
        intro: t('booth.pub.card.2.0.intro'),
        food: t('booth.pub.card.2.0.food'),
        wow: () => import('@/assets/webps/booth/wow/4.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.2.1.department'),
        intro: t('booth.pub.card.2.1.intro'),
        food: t('booth.pub.card.2.1.food'),
        wow: () => import('@/assets/webps/booth/wow/5.webp'),
        time: 'night',
      },
    ],
    3: [
      {
        department: t('booth.pub.card.3.0.department'),
        intro: t('booth.pub.card.3.0.intro'),
        event: t('booth.pub.card.3.0.event'),
        food: t('booth.pub.card.3.0.food'),
        wow: () => import('@/assets/webps/booth/wow/20.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.1.department'),
        intro: t('booth.pub.card.3.1.intro'),
        event: t('booth.pub.card.3.1.event'),
        food: t('booth.pub.card.3.1.food'),
        wow: () => import('@/assets/webps/booth/wow/21.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.2.department'),
        intro: t('booth.pub.card.3.2.intro'),
        food: t('booth.pub.card.3.2.food'),
        wow: () => import('@/assets/webps/booth/wow/22.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.3.3.department'),
        intro: t('booth.pub.card.3.3.intro'),
        event: t('booth.pub.card.3.3.event'),
        food: t('booth.pub.card.3.3.food'),
        wow: () => import('@/assets/webps/booth/wow/23.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.4.department'),
        intro: t('booth.pub.card.3.4.intro'),
        event: t('booth.pub.card.3.4.event'),
        food: t('booth.pub.card.3.4.food'),
        wow: () => import('@/assets/webps/booth/wow/24.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.5.department'),
        intro: t('booth.pub.card.3.5.intro'),
        event: t('booth.pub.card.3.5.event'),
        food: t('booth.pub.card.3.5.food'),
        wow: () => import('@/assets/webps/booth/wow/25.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.6.department'),
        intro: t('booth.pub.card.3.6.intro'),
        food: t('booth.pub.card.3.6.food'),
        wow: () => import('@/assets/webps/booth/wow/26.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.3.7.department'),
        intro: t('booth.pub.card.3.7.intro'),
        event: t('booth.pub.card.3.7.event'),
        food: t('booth.pub.card.3.7.food'),
        wow: () => import('@/assets/webps/booth/wow/27.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.8.department'),
        intro: t('booth.pub.card.3.8.intro'),
        event: t('booth.pub.card.3.8.event'),
        food: t('booth.pub.card.3.8.food'),
        wow: () => import('@/assets/webps/booth/wow/28.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.9.department'),
        intro: t('booth.pub.card.3.9.intro'),
        event: t('booth.pub.card.3.9.event'),
        food: t('booth.pub.card.3.9.food'),
        wow: () => import('@/assets/webps/booth/wow/29.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.3.10.department'),
        intro: t('booth.pub.card.3.10.intro'),
        food: t('booth.pub.card.3.10.food'),
        wow: () => import('@/assets/webps/booth/wow/30.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.3.11.department'),
        intro: t('booth.pub.card.3.11.intro'),
        event: t('booth.pub.card.3.11.event'),
        food: t('booth.pub.card.3.11.food'),
        wow: () => import('@/assets/webps/booth/wow/31.webp'),
        time: 'all',
      },
    ],
    4: [
      {
        department: t('booth.pub.card.4.0.department'),
        intro: t('booth.pub.card.4.0.intro'),
        event: t('booth.pub.card.4.0.event'),
        food: t('booth.pub.card.4.0.food'),
        wow: () => import('@/assets/webps/booth/wow/3.webp'),
        time: 'all',
      },
    ],
    5: [
      {
        department: t('booth.pub.card.5.0.department'),
        intro: t('booth.pub.card.5.0.intro'),
        food: t('booth.pub.card.5.0.food'),
        wow: () => import('@/assets/webps/booth/wow/32.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.5.1.department'),
        intro: t('booth.pub.card.5.1.intro'),
        food: t('booth.pub.card.5.1.food'),
        wow: () => import('@/assets/webps/booth/wow/33.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.5.2.department'),
        intro: t('booth.pub.card.5.2.intro'),
        food: t('booth.pub.card.5.2.food'),
        wow: () => import('@/assets/webps/booth/wow/34.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.5.3.department'),
        intro: t('booth.pub.card.5.3.intro'),
        food: t('booth.pub.card.5.3.food'),
        wow: () => import('@/assets/webps/booth/wow/35.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.5.4.department'),
        intro: t('booth.pub.card.5.4.intro'),
        food: t('booth.pub.card.5.4.food'),
        wow: () => import('@/assets/webps/booth/wow/36.webp'),
        time: 'night',
      },
    ],
    6: [
      {
        department: t('booth.pub.card.6.0.department'),
        intro: t('booth.pub.card.6.0.intro'),
        food: t('booth.pub.card.6.0.food'),
        wow: () => import('@/assets/webps/booth/wow/16.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.6.1.department'),
        intro: t('booth.pub.card.6.1.intro'),
        food: t('booth.pub.card.6.1.food'),
        wow: () => import('@/assets/webps/booth/wow/17.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.6.2.department'),
        intro: t('booth.pub.card.6.2.intro'),
        food: t('booth.pub.card.6.2.food'),
        wow: () => import('@/assets/webps/booth/wow/18.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.6.3.department'),
        intro: t('booth.pub.card.6.3.intro'),
        food: t('booth.pub.card.6.3.food'),
        wow: () => import('@/assets/webps/booth/wow/19.webp'),
        time: 'night',
      },
    ],
    7: [
      {
        department: t('booth.pub.card.7.0.department'),
        intro: t('booth.pub.card.7.0.intro'),
        food: t('booth.pub.card.7.0.food'),
        wow: () => import('@/assets/webps/booth/wow/6.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.7.1.department'),
        intro: t('booth.pub.card.7.1.intro'),
        food: t('booth.pub.card.7.1.food'),
        wow: () => import('@/assets/webps/booth/wow/7.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.7.2.department'),
        intro: t('booth.pub.card.7.2.intro'),
        food: t('booth.pub.card.7.2.food'),
        wow: () => import('@/assets/webps/booth/wow/8.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.7.3.department'),
        intro: t('booth.pub.card.7.3.intro'),
        food: t('booth.pub.card.7.3.food'),
        wow: () => import('@/assets/webps/booth/wow/9.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.7.4.department'),
        intro: t('booth.pub.card.7.4.intro'),
        food: t('booth.pub.card.7.4.food'),
        wow: () => import('@/assets/webps/booth/wow/10.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.7.5.department'),
        intro: t('booth.pub.card.7.5.intro'),
        event: t('booth.pub.card.7.5.event'),
        food: t('booth.pub.card.7.5.food'),
        wow: () => import('@/assets/webps/booth/wow/11.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.7.6.department'),
        intro: t('booth.pub.card.7.6.intro'),
        food: t('booth.pub.card.7.6.food'),
        wow: () => import('@/assets/webps/booth/wow/12.webp'),
        time: 'all',
      },
      {
        department: t('booth.pub.card.7.7.department'),
        intro: t('booth.pub.card.7.7.intro'),
        event: t('booth.pub.card.7.7.event'),
        food: t('booth.pub.card.7.7.food'),
        wow: () => import('@/assets/webps/booth/wow/13.webp'),
        time: 'all',
      },
    ],
    8: [
      {
        department: t('booth.pub.card.8.0.department'),
        intro: t('booth.pub.card.8.0.intro'),
        food: t('booth.pub.card.8.0.food'),
        wow: () => import('@/assets/webps/booth/wow/14.webp'),
        time: 'night',
      },
      {
        department: t('booth.pub.card.8.1.department'),
        intro: t('booth.pub.card.8.1.intro'),
        food: t('booth.pub.card.8.1.food'),
        wow: () => import('@/assets/webps/booth/wow/15.webp'),
        time: 'night',
      },
    ],
    9: [
      {
        department: t('booth.pub.card.9.0.department'),
        intro: t('booth.pub.card.9.0.intro'),
        event: t('booth.pub.card.9.0.event'),
        food: t('booth.pub.card.9.0.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/38.webp'),
      },
      {
        department: t('booth.pub.card.9.1.department'),
        intro: t('booth.pub.card.9.1.intro'),
        event: t('booth.pub.card.9.1.event'),
        food: t('booth.pub.card.9.1.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/39.webp'),
      },
      {
        department: t('booth.pub.card.9.2.department'),
        intro: t('booth.pub.card.9.2.intro'),
        event: t('booth.pub.card.9.2.event'),
        food: t('booth.pub.card.9.2.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/40.webp'),
      },
      {
        department: t('booth.pub.card.9.3.department'),
        intro: t('booth.pub.card.9.3.intro'),
        event: t('booth.pub.card.9.3.event'),
        food: t('booth.pub.card.9.3.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/41.webp'),
      },
    ],
    10: [
      {
        department: t('booth.pub.card.10.0.department'),
        intro: t('booth.pub.card.10.0.intro'),
        event: t('booth.pub.card.10.0.event'),
        food: t('booth.pub.card.10.0.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/42.webp'),
      },
      {
        department: t('booth.pub.card.10.1.department'),
        intro: t('booth.pub.card.10.1.intro'),
        event: t('booth.pub.card.10.1.event'),
        food: t('booth.pub.card.10.1.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/43.webp'),
      },
      {
        department: t('booth.pub.card.10.2.department'),
        intro: t('booth.pub.card.10.2.intro'),
        event: t('booth.pub.card.10.2.event'),
        food: t('booth.pub.card.10.2.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/44.webp'),
      },
      {
        department: t('booth.pub.card.10.3.department'),
        intro: t('booth.pub.card.10.3.intro'),
        event: t('booth.pub.card.10.3.event'),
        food: t('booth.pub.card.10.3.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/45.webp'),
      },
      {
        department: t('booth.pub.card.10.4.department'),
        intro: t('booth.pub.card.10.4.intro'),
        event: t('booth.pub.card.10.4.event'),
        food: t('booth.pub.card.10.4.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/46.webp'),
      },
    ],
    11: [
      {
        department: t('booth.pub.card.11.0.department'),
        intro: t('booth.pub.card.11.0.intro'),
        event: t('booth.pub.card.11.0.event'),
        food: t('booth.pub.card.11.0.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/47.webp'),
      },
      {
        department: t('booth.pub.card.11.1.department'),
        intro: t('booth.pub.card.11.1.intro'),
        event: t('booth.pub.card.11.1.event'),
        food: t('booth.pub.card.11.1.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/48.webp'),
      },
      {
        department: t('booth.pub.card.11.2.department'),
        intro: t('booth.pub.card.11.2.intro'),
        event: t('booth.pub.card.11.2.event'),
        food: t('booth.pub.card.11.2.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/49.webp'),
      },
      {
        department: t('booth.pub.card.11.3.department'),
        intro: t('booth.pub.card.11.3.intro'),
        event: t('booth.pub.card.11.3.event'),
        food: t('booth.pub.card.11.3.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/50.webp'),
      },
    ],
    12: [
      {
        department: t('booth.pub.card.12.0.department'),
        intro: t('booth.pub.card.12.0.intro'),
        event: t('booth.pub.card.12.0.event'),
        food: t('booth.pub.card.12.0.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/51.webp'),
      },
      {
        department: t('booth.pub.card.12.1.department'),
        intro: t('booth.pub.card.12.1.intro'),
        event: t('booth.pub.card.12.1.event'),
        food: t('booth.pub.card.12.1.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/52.webp'),
      },
      {
        department: t('booth.pub.card.12.2.department'),
        intro: t('booth.pub.card.12.2.intro'),
        event: t('booth.pub.card.12.2.event'),
        food: t('booth.pub.card.12.2.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/53.webp'),
      },
      {
        department: t('booth.pub.card.12.3.department'),
        intro: t('booth.pub.card.12.3.intro'),
        event: t('booth.pub.card.12.3.event'),
        food: t('booth.pub.card.12.3.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/54.webp'),
      },
    ],
    13: [
      {
        department: t('booth.pub.card.13.0.department'),
        intro: t('booth.pub.card.13.0.intro'),
        event: t('booth.pub.card.13.0.event'),
        food: t('booth.pub.card.13.0.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/55.webp'),
      },
      {
        department: t('booth.pub.card.13.1.department'),
        intro: t('booth.pub.card.13.1.intro'),
        event: t('booth.pub.card.13.1.event'),
        food: t('booth.pub.card.13.1.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/56.webp'),
      },
      {
        department: t('booth.pub.card.13.2.department'),
        intro: t('booth.pub.card.13.2.intro'),
        event: t('booth.pub.card.13.2.event'),
        food: t('booth.pub.card.13.2.food'),
        time: 'all',
        wow: () => import('@/assets/webps/booth/wow/57.webp'),
      },
    ],
  };
};
